name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Test
    runs-on: macos-12
    strategy:
      matrix:
        destination:
          - "platform=macOS"
          - "platform=iOS Simulator,name=iPhone 13 Pro"
    
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_14.1.app
      - name: Test platform ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild -scheme bs-apple-kit-Package -destination "${{ matrix.destination }}" test | xcpretty
